[package]
name = "pud"
version = "0.1.0"
authors = ["Andrei <eu@andreih.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"
gtk = { version = "0.9.2", features = ["v3_22"] }
sourceview = "0.9.0"